name: Auto Merge Feature Branches to Develop

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - develop

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    environment: Unimarket
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for auto-merge keyword
        if: contains(github.event.head_commit.message, 'AUTO-MERGE')
        run: echo "Auto-merge keyword found, proceeding with merge."

      - name: Merge feature branch into develop
        if: contains(github.event.head_commit.message, 'AUTO-MERGE')
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          source-branch: ${{ github.ref_name }}
          target-branch: develop
